# Codecov configuration to make it a bit less noisy
coverage:
  status:
    patch: false
    project:
      default: false
      tests:
        target: auto
        threshold: 15%
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null
ignore:
  - "tensorchem/util/xyz2mol.py"
